apiVersion: v1
kind: Service
metadata:
  name: hello-world-nodeport-service
  labels:
    app: hello-world
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 300