name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - master  # Trigger CI/CD when code is pushed to the 'master' branchs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run:  docker buildx build -t hello .

      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: af-south-1

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }} .
          docker push swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: get CCE Cluster Credentials
        uses: huaweicloud/cce-credential-action@v1.0.0
        with:
          ak: ${{ secrets.ACCESSKEY }}
          sk: ${{ secrets.SECRETACCESSKEY }}
          region: "af-south-1"
          project_id: "3e7cb44b-4b49-43b5-93df-d78f8a24e2dc"
          cluster_id: "974f91d7-8457-11ee-b946-0255ac100753"
          
      - name: Debugging
        run: |
          kubectl cluster-info
          kubectl get nodes
          
      - name: Update deployment
        run: |
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{github.sha }}@g" deployment.yaml 
