apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
        - name: hello-world
          image: swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:011d3690fd833f73643c6050fb8117f20c846ff0
          ports:
            - containerPort: 3000
