apiVersion: v1
kind: Service
metadata:
  name: hww
  labels:
    app: hw
spec:
  type: NodePort
  selector:
    app: hw
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30007
